server:
  port: 1249

spring:
  application:
    name: oasis
  profiles:
    active: h2
  servlet:
    multipart:
      max-file-size: ${FILE_MAX_SIZE:500MB}
      max-request-size: ${FILE_MAX_REQUEST:500MB}

jdevelops:
  jwt:
    prefix: ${spring.application.name}
    token-secret: b4c12a6f172f13f91500b6c437a78d2cc5e5f9973e7dee431a1e8c34e68d365e
  swagger:
    base-package:
      - cn.tannn.oasis.controller
    title: ${spring.application.name}
    display-name: 导航
    group-name: oasis
#    security-scheme-default: false

knife4j:
  enable: true
  setting:
    language: zh-CN
    custom-code: 500
    enable-footer-custom: false
    enable-dynamic-parameter: true
  basic:
    enable: true
    password: ${DOC_PASSWORD:tan}
    username: ${DOC_USERNAME:tan}
    include:
      - /v3;/api-docs
oasis:
  config:
    def-password: ${OASIS_DEF_PWD:123}
    def-username: ${OASIS_DEF_UNAME:tan}
    def-site-title: ${OASIS_DEF_SITE_TITLE:Oasis}
